// Generated by https://quicktype.io

import { ExternalUrls } from '../../shared/types/shared.types';

export interface Playlist {
  collaborative: boolean;
  description: string;
  external_urls: ExternalUrls;
  href: string;
  id: string;
  images: PlaylistImage[];
  name: string;
  owner: PlaylistOwner;
  primary_color: any;
  public: boolean;
  snapshot_id: string;
  tracks: PlaylistTracks;
  type: string;
  uri: string;
}

export interface PlaylistImage {
  height: number;
  url: string;
  width: number;
}

export interface PlaylistOwner {
  display_name: string;
  external_urls: ExternalUrls;
  href: string;
  id: string;
  type: string;
  uri: string;
}

export interface PlaylistTracks {
  href: string;
  total: number;
}

export interface PlaylistsGetParams {
  limit: number;
  offset: number;
}

export interface PlaylistsGetResponse {
  href: string;
  items: Playlist[];
  limit: number;
  next: string;
  offset: number;
  previous: string;
  total: number;
}

export type Playlists = Pick<
  PlaylistsGetResponse,
  'items' | 'limit' | 'offset' | 'total'
>;
