// Components
import Header from '../shared/components/Header/Header';
import Sidebar from '../shared/components/Sidebar/Sidebar';

// Providers
import BackgroundProvider from '../shared/providers/BackgroundProvider';
import ThemeProvider from '../shared/providers/ThemeProvider';
import ReactQueryProvider from '../shared/providers/ReactQuerryProvider';
import SessionProvider from '../shared/providers/SessionProvider';

// Styles
import styles from './RootLayout.module.scss';
import '../shared/styles/globals.scss';

// async function getPlaylists(): Promise<PlaylistsResponse | undefined> {
//   const session: SpotilibSession | null = await unstable_getServerSession(
//     authOptions
//   );

//   if (session?.token?.accessToken) {
//     const params = new URLSearchParams({
//       limit: '25',
//     }).toString();

//     const url = `https://api.spotify.com/v1/users/${
//       session?.token?.providerAccountId
//     }/playlists${params && params?.length > 0 ? `?${params}` : ''}`;

//     const res = await fetch(url, {
//       headers: {
//         Authorization: `Bearer ${session?.token?.accessToken}`,
//         'Content-Type': 'application/json',
//         Accept: 'application/json',
//       },
//     });
//     return res.json();
//   } else {
//     return Promise.resolve(undefined);
//   }
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const playlists = await getPlaylists();
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={styles['root-layout']} id="__next">
        <ReactQueryProvider>
          <SessionProvider>
            <ThemeProvider>
              <BackgroundProvider>
                <Header />
                <div className={styles['root-layout-page-content']}>
                  <Sidebar />
                  <div className={styles['root-layout-page-content-main']}>
                    {children}
                  </div>
                </div>
              </BackgroundProvider>
            </ThemeProvider>
          </SessionProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
