// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "common": {
    "menu": {
      "login": "Login",
      "logout": "Logout",
      "privacy": "Privacy"
    },
    "nav": {
      "about": "About us",
      "faq": "FAQ",
      "home": "Home",
      "imprint": "Imprint",
      "posts": "Posts",
      "profile": "Profile"
    },
    "settings": {
      "language": {
        "de": "German (DE)",
        "en": "English (EN)",
        "title": "Change language"
      },
      "theme": {
        "dark": "Dark theme",
        "light": "Light theme",
        "system": "System theme",
        "title": "Change theme"
      }
    }
  },
  "home": {
    "title": "Welcome"
  },
  "posts": {
    "title": "Posts"
  }
};
export default messages;