// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "artists": {
    "card": {
      "menu": {
        "add": "Add to library",
        "remove": "Remove from library"
      }
    },
    "title": "Artists"
  },
  "common": {
    "menu": {
      "logout": "Logout",
      "privacy": "Privacy",
      "profile": "Profile"
    },
    "nav": {
      "about": "About us",
      "artists": "Artists",
      "faq": "FAQ",
      "home": "Home",
      "imprint": "Imprint",
      "posts": "Posts"
    },
    "search": "What do you want to search?",
    "settings": {
      "language": {
        "de": "German (DE)",
        "en": "English (EN)",
        "title": "Change language"
      },
      "theme": {
        "dark": "Dark theme",
        "light": "Light theme",
        "system": "System theme",
        "title": "Change theme"
      }
    }
  },
  "home": {
    "title": "Welcome"
  },
  "login": {
    "button": "Sign in with Spotify"
  },
  "posts": {
    "title": "Posts"
  },
  "user": {
    "followers": "Follow:innen"
  }
};
export default messages;