import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { getServerSession } from 'next-auth';
import { unstable_setRequestLocale } from 'next-intl/server';

// Components
import Nav from '@/components/Nav/Nav';

// Providers
import QueryClientProvider from '@/providers/QueryClientProvider';
import SessionProvider from '@/providers/SessionProvider';

// Styles
import './globals.scss';

// Theme
import ThemeRegistry from '@/theme/ThemeRegistry';

const locales = ['en', 'de'];

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: ReactNode;
  params: { locale: string };
}) {
  const session = await getServerSession();

  // Validate that the incoming `locale` parameter is valid
  const isValidLocale = locales.some((cur) => cur === locale);
  if (!isValidLocale) notFound();

  unstable_setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body>
        <SessionProvider session={session}>
          <QueryClientProvider>
            <Nav locale={locale} />
            <ThemeRegistry options={{ key: 'mui' }}>{children}</ThemeRegistry>
          </QueryClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
